name: CD 
on: 
  workflow_run: 
    workflows: ['CI']
    types: 
      - completed 


  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Push to Hugging Face via Git
        env:
          HF_TOKEN: ${{ secrets.HF }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions Bot"

          git clone https://DANISHFAYAZNAJAR:${HF_TOKEN}@huggingface.co/spaces/DANISHFAYAZNAJAR/drug-classification
          cd drug-classification

          cp -r ../App ./App
          cp -r ../Model ./Model
          cp -r ../Results ./Metrics

          git add .
          git commit -m "Sync all files"
          git push
